spring:
  application:
    name: ms-notification
  datasource:
    url: jdbc:mysql://localhost:3300/challenge3-ms-notification?createDatabaseIfNotExist=true
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: challengethreecompass@gmail.com
    password: oyjhoxfpfvckncse
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  name: Email

exchange:
  name: amq.direct
routing:
  key: email

server:
  port: 8050

logging:
  level:
    org:
      springframework:
        web: DEBUG
