version: '3.1'

services:
  mysql:
    image: mysql:8.0.31
    container_name: 'mysql-db'
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - '3300:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge3-ms-products

  rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: 'rabbitmq-management'
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  mysql-volume: