spring:
  application:
    name: ms-products
  datasource:
    url: jdbc:mysql://localhost:3300/challenge3-ms-products?createDatabaseIfNotExist=true
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080