spring:
  application:
    name: ms-auth

feign:
  client:
    config:
      default:
        connectionTimeout: 5000
        readTimeout: 5000

server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka